### YamlMime:ManagedReference
items:
- uid: Discord.Rest.DiscordRestConfig
  commentId: T:Discord.Rest.DiscordRestConfig
  id: DiscordRestConfig
  parent: Discord.Rest
  children:
  - Discord.Rest.DiscordRestConfig.RestClientProvider
  langs:
  - csharp
  - vb
  name: DiscordRestConfig
  nameWithType: DiscordRestConfig
  fullName: Discord.Rest.DiscordRestConfig
  type: Class
  source:
    remote:
      path: src/Discord.Net.Rest/DiscordRestConfig.cs
      branch: dev
      repo: https://github.com/discord-net/Discord.Net
    id: DiscordRestConfig
    path: ../src/Discord.Net.Rest/DiscordRestConfig.cs
    startLine: 7
  assemblies:
  - Discord.Net.Rest
  namespace: Discord.Rest
  summary: "\nRepresents a configuration class for <xref href=\"Discord.Rest.DiscordRestClient\" data-throw-if-not-resolved=\"false\"></xref>.\n"
  example: []
  syntax:
    content: 'public class DiscordRestConfig : DiscordConfig'
    content.vb: >-
      Public Class DiscordRestConfig
          Inherits DiscordConfig
  inheritance:
  - System.Object
  - Discord.DiscordConfig
  derivedClasses:
  - Discord.WebSocket.DiscordSocketConfig
  inheritedMembers:
  - Discord.DiscordConfig.APIVersion
  - Discord.DiscordConfig.VoiceAPIVersion
  - Discord.DiscordConfig.Version
  - Discord.DiscordConfig.UserAgent
  - Discord.DiscordConfig.APIUrl
  - Discord.DiscordConfig.CDNUrl
  - Discord.DiscordConfig.InviteUrl
  - Discord.DiscordConfig.DefaultRequestTimeout
  - Discord.DiscordConfig.MaxMessageSize
  - Discord.DiscordConfig.MaxMessagesPerBatch
  - Discord.DiscordConfig.MaxUsersPerBatch
  - Discord.DiscordConfig.MaxGuildsPerBatch
  - Discord.DiscordConfig.MaxUserReactionsPerBatch
  - Discord.DiscordConfig.MaxAuditLogEntriesPerBatch
  - Discord.DiscordConfig.DefaultRetryMode
  - Discord.DiscordConfig.LogLevel
  - Discord.DiscordConfig.RateLimitPrecision
  - Discord.DiscordConfig.UseSystemClock
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Discord.Rest.DiscordRestConfig.RestClientProvider
  commentId: P:Discord.Rest.DiscordRestConfig.RestClientProvider
  id: RestClientProvider
  parent: Discord.Rest.DiscordRestConfig
  langs:
  - csharp
  - vb
  name: RestClientProvider
  nameWithType: DiscordRestConfig.RestClientProvider
  fullName: Discord.Rest.DiscordRestConfig.RestClientProvider
  type: Property
  source:
    remote:
      path: src/Discord.Net.Rest/DiscordRestConfig.cs
      branch: dev
      repo: https://github.com/discord-net/Discord.Net
    id: RestClientProvider
    path: ../src/Discord.Net.Rest/DiscordRestConfig.cs
    startLine: 10
  assemblies:
  - Discord.Net.Rest
  namespace: Discord.Rest
  summary: 'Gets or sets the provider used to generate new REST connections. '
  example: []
  syntax:
    content: public RestClientProvider RestClientProvider { get; set; }
    parameters: []
    return:
      type: Discord.Net.Rest.RestClientProvider
    content.vb: Public Property RestClientProvider As RestClientProvider
  overload: Discord.Rest.DiscordRestConfig.RestClientProvider*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Discord.Rest.DiscordRestClient
  commentId: T:Discord.Rest.DiscordRestClient
  parent: Discord.Rest
  name: DiscordRestClient
  nameWithType: DiscordRestClient
  fullName: Discord.Rest.DiscordRestClient
- uid: Discord.Rest
  commentId: N:Discord.Rest
  name: Discord.Rest
  nameWithType: Discord.Rest
  fullName: Discord.Rest
- uid: System.Object
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Discord.DiscordConfig
  commentId: T:Discord.DiscordConfig
  parent: Discord
  name: DiscordConfig
  nameWithType: DiscordConfig
  fullName: Discord.DiscordConfig
- uid: Discord.DiscordConfig.APIVersion
  commentId: F:Discord.DiscordConfig.APIVersion
  parent: Discord.DiscordConfig
  name: APIVersion
  nameWithType: DiscordConfig.APIVersion
  fullName: Discord.DiscordConfig.APIVersion
- uid: Discord.DiscordConfig.VoiceAPIVersion
  commentId: F:Discord.DiscordConfig.VoiceAPIVersion
  parent: Discord.DiscordConfig
  name: VoiceAPIVersion
  nameWithType: DiscordConfig.VoiceAPIVersion
  fullName: Discord.DiscordConfig.VoiceAPIVersion
- uid: Discord.DiscordConfig.Version
  commentId: P:Discord.DiscordConfig.Version
  parent: Discord.DiscordConfig
  name: Version
  nameWithType: DiscordConfig.Version
  fullName: Discord.DiscordConfig.Version
- uid: Discord.DiscordConfig.UserAgent
  commentId: P:Discord.DiscordConfig.UserAgent
  parent: Discord.DiscordConfig
  name: UserAgent
  nameWithType: DiscordConfig.UserAgent
  fullName: Discord.DiscordConfig.UserAgent
- uid: Discord.DiscordConfig.APIUrl
  commentId: F:Discord.DiscordConfig.APIUrl
  parent: Discord.DiscordConfig
  name: APIUrl
  nameWithType: DiscordConfig.APIUrl
  fullName: Discord.DiscordConfig.APIUrl
- uid: Discord.DiscordConfig.CDNUrl
  commentId: F:Discord.DiscordConfig.CDNUrl
  parent: Discord.DiscordConfig
  name: CDNUrl
  nameWithType: DiscordConfig.CDNUrl
  fullName: Discord.DiscordConfig.CDNUrl
- uid: Discord.DiscordConfig.InviteUrl
  commentId: F:Discord.DiscordConfig.InviteUrl
  parent: Discord.DiscordConfig
  name: InviteUrl
  nameWithType: DiscordConfig.InviteUrl
  fullName: Discord.DiscordConfig.InviteUrl
- uid: Discord.DiscordConfig.DefaultRequestTimeout
  commentId: F:Discord.DiscordConfig.DefaultRequestTimeout
  parent: Discord.DiscordConfig
  name: DefaultRequestTimeout
  nameWithType: DiscordConfig.DefaultRequestTimeout
  fullName: Discord.DiscordConfig.DefaultRequestTimeout
- uid: Discord.DiscordConfig.MaxMessageSize
  commentId: F:Discord.DiscordConfig.MaxMessageSize
  parent: Discord.DiscordConfig
  name: MaxMessageSize
  nameWithType: DiscordConfig.MaxMessageSize
  fullName: Discord.DiscordConfig.MaxMessageSize
- uid: Discord.DiscordConfig.MaxMessagesPerBatch
  commentId: F:Discord.DiscordConfig.MaxMessagesPerBatch
  parent: Discord.DiscordConfig
  name: MaxMessagesPerBatch
  nameWithType: DiscordConfig.MaxMessagesPerBatch
  fullName: Discord.DiscordConfig.MaxMessagesPerBatch
- uid: Discord.DiscordConfig.MaxUsersPerBatch
  commentId: F:Discord.DiscordConfig.MaxUsersPerBatch
  parent: Discord.DiscordConfig
  name: MaxUsersPerBatch
  nameWithType: DiscordConfig.MaxUsersPerBatch
  fullName: Discord.DiscordConfig.MaxUsersPerBatch
- uid: Discord.DiscordConfig.MaxGuildsPerBatch
  commentId: F:Discord.DiscordConfig.MaxGuildsPerBatch
  parent: Discord.DiscordConfig
  name: MaxGuildsPerBatch
  nameWithType: DiscordConfig.MaxGuildsPerBatch
  fullName: Discord.DiscordConfig.MaxGuildsPerBatch
- uid: Discord.DiscordConfig.MaxUserReactionsPerBatch
  commentId: F:Discord.DiscordConfig.MaxUserReactionsPerBatch
  parent: Discord.DiscordConfig
  name: MaxUserReactionsPerBatch
  nameWithType: DiscordConfig.MaxUserReactionsPerBatch
  fullName: Discord.DiscordConfig.MaxUserReactionsPerBatch
- uid: Discord.DiscordConfig.MaxAuditLogEntriesPerBatch
  commentId: F:Discord.DiscordConfig.MaxAuditLogEntriesPerBatch
  parent: Discord.DiscordConfig
  name: MaxAuditLogEntriesPerBatch
  nameWithType: DiscordConfig.MaxAuditLogEntriesPerBatch
  fullName: Discord.DiscordConfig.MaxAuditLogEntriesPerBatch
- uid: Discord.DiscordConfig.DefaultRetryMode
  commentId: P:Discord.DiscordConfig.DefaultRetryMode
  parent: Discord.DiscordConfig
  name: DefaultRetryMode
  nameWithType: DiscordConfig.DefaultRetryMode
  fullName: Discord.DiscordConfig.DefaultRetryMode
- uid: Discord.DiscordConfig.LogLevel
  commentId: P:Discord.DiscordConfig.LogLevel
  parent: Discord.DiscordConfig
  name: LogLevel
  nameWithType: DiscordConfig.LogLevel
  fullName: Discord.DiscordConfig.LogLevel
- uid: Discord.DiscordConfig.RateLimitPrecision
  commentId: P:Discord.DiscordConfig.RateLimitPrecision
  parent: Discord.DiscordConfig
  name: RateLimitPrecision
  nameWithType: DiscordConfig.RateLimitPrecision
  fullName: Discord.DiscordConfig.RateLimitPrecision
- uid: Discord.DiscordConfig.UseSystemClock
  commentId: P:Discord.DiscordConfig.UseSystemClock
  parent: Discord.DiscordConfig
  name: UseSystemClock
  nameWithType: DiscordConfig.UseSystemClock
  fullName: Discord.DiscordConfig.UseSystemClock
- uid: Discord
  commentId: N:Discord
  name: Discord
  nameWithType: Discord
  fullName: Discord
- uid: Discord.Rest.DiscordRestConfig.RestClientProvider*
  commentId: Overload:Discord.Rest.DiscordRestConfig.RestClientProvider
  name: RestClientProvider
  nameWithType: DiscordRestConfig.RestClientProvider
  fullName: Discord.Rest.DiscordRestConfig.RestClientProvider
- uid: Discord.Net.Rest.RestClientProvider
  commentId: T:Discord.Net.Rest.RestClientProvider
  parent: Discord.Net.Rest
  name: RestClientProvider
  nameWithType: RestClientProvider
  fullName: Discord.Net.Rest.RestClientProvider
- uid: Discord.Net.Rest
  commentId: N:Discord.Net.Rest
  name: Discord.Net.Rest
  nameWithType: Discord.Net.Rest
  fullName: Discord.Net.Rest
