### YamlMime:ManagedReference
items:
- uid: Discord.Audio.AudioApplication
  commentId: T:Discord.Audio.AudioApplication
  id: AudioApplication
  parent: Discord.Audio
  children:
  - Discord.Audio.AudioApplication.Mixed
  - Discord.Audio.AudioApplication.Music
  - Discord.Audio.AudioApplication.Voice
  langs:
  - csharp
  - vb
  name: AudioApplication
  nameWithType: AudioApplication
  fullName: Discord.Audio.AudioApplication
  type: Enum
  source:
    remote:
      path: src/Discord.Net.Core/Audio/AudioApplication.cs
      branch: dev
      repo: https://github.com/discord-net/Discord.Net
    id: AudioApplication
    path: ../src/Discord.Net.Core/Audio/AudioApplication.cs
    startLine: 2
  assemblies:
  - Discord.Net.Core
  namespace: Discord.Audio
  syntax:
    content: public enum AudioApplication
    content.vb: Public Enum AudioApplication
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: Discord.Audio.AudioApplication.Voice
  commentId: F:Discord.Audio.AudioApplication.Voice
  id: Voice
  parent: Discord.Audio.AudioApplication
  langs:
  - csharp
  - vb
  name: Voice
  nameWithType: AudioApplication.Voice
  fullName: Discord.Audio.AudioApplication.Voice
  type: Field
  source:
    remote:
      path: src/Discord.Net.Core/Audio/AudioApplication.cs
      branch: dev
      repo: https://github.com/discord-net/Discord.Net
    id: Voice
    path: ../src/Discord.Net.Core/Audio/AudioApplication.cs
    startLine: 4
  assemblies:
  - Discord.Net.Core
  namespace: Discord.Audio
  syntax:
    content: Voice = 0
    return:
      type: Discord.Audio.AudioApplication
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Discord.Audio.AudioApplication.Music
  commentId: F:Discord.Audio.AudioApplication.Music
  id: Music
  parent: Discord.Audio.AudioApplication
  langs:
  - csharp
  - vb
  name: Music
  nameWithType: AudioApplication.Music
  fullName: Discord.Audio.AudioApplication.Music
  type: Field
  source:
    remote:
      path: src/Discord.Net.Core/Audio/AudioApplication.cs
      branch: dev
      repo: https://github.com/discord-net/Discord.Net
    id: Music
    path: ../src/Discord.Net.Core/Audio/AudioApplication.cs
    startLine: 5
  assemblies:
  - Discord.Net.Core
  namespace: Discord.Audio
  syntax:
    content: Music = 1
    return:
      type: Discord.Audio.AudioApplication
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Discord.Audio.AudioApplication.Mixed
  commentId: F:Discord.Audio.AudioApplication.Mixed
  id: Mixed
  parent: Discord.Audio.AudioApplication
  langs:
  - csharp
  - vb
  name: Mixed
  nameWithType: AudioApplication.Mixed
  fullName: Discord.Audio.AudioApplication.Mixed
  type: Field
  source:
    remote:
      path: src/Discord.Net.Core/Audio/AudioApplication.cs
      branch: dev
      repo: https://github.com/discord-net/Discord.Net
    id: Mixed
    path: ../src/Discord.Net.Core/Audio/AudioApplication.cs
    startLine: 6
  assemblies:
  - Discord.Net.Core
  namespace: Discord.Audio
  syntax:
    content: Mixed = 2
    return:
      type: Discord.Audio.AudioApplication
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: Discord.Audio
  commentId: N:Discord.Audio
  name: Discord.Audio
  nameWithType: Discord.Audio
  fullName: Discord.Audio
- uid: Discord.Audio.AudioApplication
  commentId: T:Discord.Audio.AudioApplication
  parent: Discord.Audio
  name: AudioApplication
  nameWithType: AudioApplication
  fullName: Discord.Audio.AudioApplication
