### YamlMime:ManagedReference
items:
- uid: Discord.MessageApplication
  commentId: T:Discord.MessageApplication
  id: MessageApplication
  parent: Discord
  children:
  - Discord.MessageApplication.CoverImage
  - Discord.MessageApplication.Description
  - Discord.MessageApplication.Icon
  - Discord.MessageApplication.IconUrl
  - Discord.MessageApplication.Id
  - Discord.MessageApplication.Name
  - Discord.MessageApplication.ToString
  langs:
  - csharp
  - vb
  name: MessageApplication
  nameWithType: MessageApplication
  fullName: Discord.MessageApplication
  type: Class
  source:
    remote:
      path: src/Discord.Net.Core/Entities/Messages/MessageApplication.cs
      branch: dev
      repo: https://github.com/discord-net/Discord.Net
    id: MessageApplication
    path: ../src/Discord.Net.Core/Entities/Messages/MessageApplication.cs
    startLine: 4
  assemblies:
  - Discord.Net.Core
  namespace: Discord
  syntax:
    content: 'public class MessageApplication : object'
    content.vb: >-
      Public Class MessageApplication
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Discord.MessageApplication.Id
  commentId: P:Discord.MessageApplication.Id
  id: Id
  parent: Discord.MessageApplication
  langs:
  - csharp
  - vb
  name: Id
  nameWithType: MessageApplication.Id
  fullName: Discord.MessageApplication.Id
  type: Property
  source:
    remote:
      path: src/Discord.Net.Core/Entities/Messages/MessageApplication.cs
      branch: dev
      repo: https://github.com/discord-net/Discord.Net
    id: Id
    path: ../src/Discord.Net.Core/Entities/Messages/MessageApplication.cs
    startLine: 10
  assemblies:
  - Discord.Net.Core
  namespace: Discord
  summary: "\nGets the snowflake ID of the application.\n"
  example: []
  syntax:
    content: public ulong Id { get; }
    parameters: []
    return:
      type: System.UInt64
    content.vb: Public ReadOnly Property Id As ULong
  overload: Discord.MessageApplication.Id*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Discord.MessageApplication.CoverImage
  commentId: P:Discord.MessageApplication.CoverImage
  id: CoverImage
  parent: Discord.MessageApplication
  langs:
  - csharp
  - vb
  name: CoverImage
  nameWithType: MessageApplication.CoverImage
  fullName: Discord.MessageApplication.CoverImage
  type: Property
  source:
    remote:
      path: src/Discord.Net.Core/Entities/Messages/MessageApplication.cs
      branch: dev
      repo: https://github.com/discord-net/Discord.Net
    id: CoverImage
    path: ../src/Discord.Net.Core/Entities/Messages/MessageApplication.cs
    startLine: 14
  assemblies:
  - Discord.Net.Core
  namespace: Discord
  summary: "\nGets the ID of the embed&apos;s image asset.\n"
  example: []
  syntax:
    content: public string CoverImage { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public ReadOnly Property CoverImage As String
  overload: Discord.MessageApplication.CoverImage*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Discord.MessageApplication.Description
  commentId: P:Discord.MessageApplication.Description
  id: Description
  parent: Discord.MessageApplication
  langs:
  - csharp
  - vb
  name: Description
  nameWithType: MessageApplication.Description
  fullName: Discord.MessageApplication.Description
  type: Property
  source:
    remote:
      path: src/Discord.Net.Core/Entities/Messages/MessageApplication.cs
      branch: dev
      repo: https://github.com/discord-net/Discord.Net
    id: Description
    path: ../src/Discord.Net.Core/Entities/Messages/MessageApplication.cs
    startLine: 18
  assemblies:
  - Discord.Net.Core
  namespace: Discord
  summary: "\nGets the application&apos;s description.\n"
  example: []
  syntax:
    content: public string Description { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public ReadOnly Property Description As String
  overload: Discord.MessageApplication.Description*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Discord.MessageApplication.Icon
  commentId: P:Discord.MessageApplication.Icon
  id: Icon
  parent: Discord.MessageApplication
  langs:
  - csharp
  - vb
  name: Icon
  nameWithType: MessageApplication.Icon
  fullName: Discord.MessageApplication.Icon
  type: Property
  source:
    remote:
      path: src/Discord.Net.Core/Entities/Messages/MessageApplication.cs
      branch: dev
      repo: https://github.com/discord-net/Discord.Net
    id: Icon
    path: ../src/Discord.Net.Core/Entities/Messages/MessageApplication.cs
    startLine: 22
  assemblies:
  - Discord.Net.Core
  namespace: Discord
  summary: "\nGets the ID of the application&apos;s icon.\n"
  example: []
  syntax:
    content: public string Icon { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public ReadOnly Property Icon As String
  overload: Discord.MessageApplication.Icon*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Discord.MessageApplication.IconUrl
  commentId: P:Discord.MessageApplication.IconUrl
  id: IconUrl
  parent: Discord.MessageApplication
  langs:
  - csharp
  - vb
  name: IconUrl
  nameWithType: MessageApplication.IconUrl
  fullName: Discord.MessageApplication.IconUrl
  type: Property
  source:
    remote:
      path: src/Discord.Net.Core/Entities/Messages/MessageApplication.cs
      branch: dev
      repo: https://github.com/discord-net/Discord.Net
    id: IconUrl
    path: ../src/Discord.Net.Core/Entities/Messages/MessageApplication.cs
    startLine: 26
  assemblies:
  - Discord.Net.Core
  namespace: Discord
  summary: "\nGets the Url of the application&apos;s icon.\n"
  example: []
  syntax:
    content: public string IconUrl { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public ReadOnly Property IconUrl As String
  overload: Discord.MessageApplication.IconUrl*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Discord.MessageApplication.Name
  commentId: P:Discord.MessageApplication.Name
  id: Name
  parent: Discord.MessageApplication
  langs:
  - csharp
  - vb
  name: Name
  nameWithType: MessageApplication.Name
  fullName: Discord.MessageApplication.Name
  type: Property
  source:
    remote:
      path: src/Discord.Net.Core/Entities/Messages/MessageApplication.cs
      branch: dev
      repo: https://github.com/discord-net/Discord.Net
    id: Name
    path: ../src/Discord.Net.Core/Entities/Messages/MessageApplication.cs
    startLine: 31
  assemblies:
  - Discord.Net.Core
  namespace: Discord
  summary: "\nGets the name of the application.\n"
  example: []
  syntax:
    content: public string Name { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public ReadOnly Property Name As String
  overload: Discord.MessageApplication.Name*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Discord.MessageApplication.ToString
  commentId: M:Discord.MessageApplication.ToString
  id: ToString
  parent: Discord.MessageApplication
  langs:
  - csharp
  - vb
  name: ToString()
  nameWithType: MessageApplication.ToString()
  fullName: Discord.MessageApplication.ToString()
  type: Method
  source:
    remote:
      path: src/Discord.Net.Core/Entities/Messages/MessageApplication.cs
      branch: dev
      repo: https://github.com/discord-net/Discord.Net
    id: ToString
    path: ../src/Discord.Net.Core/Entities/Messages/MessageApplication.cs
    startLine: 34
  assemblies:
  - Discord.Net.Core
  namespace: Discord
  syntax:
    content: public override string ToString()
    return:
      type: System.String
    content.vb: Public Overrides Function ToString As String
  overload: Discord.MessageApplication.ToString*
  modifiers.csharp:
  - public
  - override
  modifiers.vb:
  - Public
  - Overrides
references:
- uid: Discord
  commentId: N:Discord
  name: Discord
  nameWithType: Discord
  fullName: Discord
- uid: System.Object
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Discord.MessageApplication.Id*
  commentId: Overload:Discord.MessageApplication.Id
  name: Id
  nameWithType: MessageApplication.Id
  fullName: Discord.MessageApplication.Id
- uid: System.UInt64
  isExternal: true
  name: UInt64
  nameWithType: UInt64
  fullName: System.UInt64
- uid: Discord.MessageApplication.CoverImage*
  commentId: Overload:Discord.MessageApplication.CoverImage
  name: CoverImage
  nameWithType: MessageApplication.CoverImage
  fullName: Discord.MessageApplication.CoverImage
- uid: System.String
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Discord.MessageApplication.Description*
  commentId: Overload:Discord.MessageApplication.Description
  name: Description
  nameWithType: MessageApplication.Description
  fullName: Discord.MessageApplication.Description
- uid: Discord.MessageApplication.Icon*
  commentId: Overload:Discord.MessageApplication.Icon
  name: Icon
  nameWithType: MessageApplication.Icon
  fullName: Discord.MessageApplication.Icon
- uid: Discord.MessageApplication.IconUrl*
  commentId: Overload:Discord.MessageApplication.IconUrl
  name: IconUrl
  nameWithType: MessageApplication.IconUrl
  fullName: Discord.MessageApplication.IconUrl
- uid: Discord.MessageApplication.Name*
  commentId: Overload:Discord.MessageApplication.Name
  name: Name
  nameWithType: MessageApplication.Name
  fullName: Discord.MessageApplication.Name
- uid: Discord.MessageApplication.ToString*
  commentId: Overload:Discord.MessageApplication.ToString
  name: ToString
  nameWithType: MessageApplication.ToString
  fullName: Discord.MessageApplication.ToString
